---
# tasks file for kfieldho.cmake

- name: Copy goss tests template
  template:
    src: test_cmake.yml.j2
    dest: /root/test_cmake.yml

- name: Check to See if CMake root exists
  stat:
    path: "{{ cmake_dest_dir }}"
  register: opt_kitware

- name: Ensure installation directory
  become: true
  file:
    state: directory
    mode: 0755
    dest: "{{ cmake_dest_dir }}"
  when: not opt_kitware.stat.exists

- name: Check to See if CMake is already installed
  stat:
    path: "{{ cmake_install_dir }}/bin/cmake"
  register: bin_cmake
  changed_when: false

- name: Download CMake
  get_url:
    url: "{{ cmake_url }}"
    dest: "{{ cmake_temp }}"
    validate_certs: false
  register: cmake_downloaded
  until: cmake_downloaded is success
  retries: 10
  delay: 2
  when: not bin_cmake.stat.exists

- name: Install CMake
  unarchive:
    copy: false
    src: "{{ cmake_temp }}"
    dest: "{{ cmake_dest_dir }}"
  become: true
  when: (not bin_cmake.stat.exists)

- name: Verify if CMAke rcfile exists
  stat:
    path: "{{ cmake_rcfile }}"
  register: cmake_profile

- name: Ensure CMake rcfile exists
  become: true
  when: not cmake_profile.stat.exists
  file:
    path: "{{ cmake_rcfile }}"
    owner: root
    group: root
    mode: 0644
    state: touch

- name: ensure current symlink exists
  file:
    src: "{{ cmake_install_dir }}"
    dest: "{{ cmake_dest_dir }}/current"
    state: link
    owner: root
    group: root
  tags:
    - symlink

- name: ensure kitware symlink exists
  file:
    src: "{{ cmake_dest_dir }}"
    dest: /opt/kitware
    state: link
    owner: root
    group: root
  tags:
    - symlink

- name: Add CMake to everyone's PATH
  when: cmake_modify_path|bool
  become: true
  blockinfile:
    state: present
    dest: "{{ cmake_rcfile }}"
    block: |
      export PATH={{ cmake_install_dir }}bin:$PATH
      export CMAKE_HOME={{ cmake_install_dir }}
